@port = 5000
@hostname = http://localhost
@host = {{hostname}}:{{port}}/api
@email = ONE@wp.pl
@password = bbb

# @name signUp
POST {{host}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "firstname": "John",
    "surname": "Doe",
    "email": "{{email}}",
    "password": "{{password}}",
    "nip": "0123456789",
    "city": "City",
    "postalCode": "00-000",
    "buildingNumber": "1",
    "street": "street",
    "phone": "+48123456789"
}

###
@token = {{signUp.response.body.access_token}}

# @name signIn
POST {{host}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
@token = {{signIn.response.body.access_token}}

# Przykład wykorzystania `@jwt_required()` - zabezpieczenie endpoint'u
# @name secured
POST {{host}}/auth/secured HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json