@port = 5000
@hostname = http://localhost
@host = {{hostname}}:{{port}}/api
@email = john.doe@wp.pl
@password = myjohn

# @name signUp
POST {{host}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "customer_firstname": "John",
    "customer_surname": "Doe",
    "customer_email": "{{email}}",
    "customer_password": "{{password}}",
    "customer_nip_number": "0123456789",
    "customer_city": "City",
    "customer_postal_code": "00-000",
    "customer_building_number": "1",
    "customer_street": "street",
    "customer_phone": "+48123456789"
}

###
@token = {{signUp.response.body.access_token}}
@auth_schema = {{signUp.response.body.auth_schema}}

# @name signIn
POST {{host}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
@token = {{signIn.response.body.access_token}}
@auth_schema = {{signIn.response.body.auth_schema}}

# Przykład wykorzystania `@jwt_required()` - zabezpieczenie endpoint'u
# @name secured
POST {{host}}/auth/secured HTTP/1.1
Authorization: {{auth_schema}} {{token}}
Content-Type: application/json

