@port = 5000
@hostname = http://localhost
@host = {{hostname}}:{{port}}/api
@email = ADMIN
@password = mypass

# @name signUp
POST {{host}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "customer_firstname": "John",
    "customer_surname": "Doe",
    "customer_email": "{{email}}",
    "customer_password": "{{password}}",
    "customer_nip_number": "0123456789",
    "customer_city": "City",
    "customer_postal_code": "00-000",
    "customer_building_number": "1",
    "customer_street": "street",
    "customer_phone": "+48123456789"
}

###
@token = {{signUp.response.body.access_token}}

# @name signIn
POST {{host}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
@token = {{signIn.response.body.access_token}}

# Przykład wykorzystania `@jwt_required()` - zabezpieczenie endpoint'u
# @name secured
POST {{host}}/auth/secured HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json


###
@token = {{signUp.response.body.access_token}}

# @name signIn
GET {{host}}/admin/service HTTP/1.1
Content-Type: application/json
